name: deploy
on: 
  workflow_dispatch:
  push:
   branches:
     - main
jobs:
  build-web-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Building React.js Web UI
        uses: actions/checkout@v2
      - run: cd frontend && npm install && npm run build
  deploying:
    runs-on: ubuntu-latest
    needs: build-web-ui
    steps:
    - name: Deploying Web UI Changes via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: 22
        script: |
          cd ${{secrets.DEPLOY_PATH}}
          git pull
          cd frontend
          npm run build
          echo ${{secrets.SUDO_PASSWORD}} | sudo -S service cake restart
        key: ${{ secrets.FZ_SSH_PRIVATE_KEY }} 

  