name: Deploy Web UI to Server
on: 
  push:
   branches:
     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Changes via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: 22
        script: |
          cd ${{secrets.DEPLOY_PATH}}
          git pull
          cd frontend
          npm build
          service cake restart
        key: ${{ secrets.FZ_SSH_PRIVATE_KEY }} 

  